package org.victor.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.victor.model.Flight;
import org.victor.model.FlightExample;

public interface FlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int countByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int deleteByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    @Delete({
        "delete from Flight",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    @Insert({
        "insert into Flight (id, type, ",
        "name)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR})"
    })
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int insertSelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    List<Flight> selectByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, type, name",
        "from Flight",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Flight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Flight
     *
     * @mbggenerated
     */
    @Update({
        "update Flight",
        "set type = #{type,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Flight record);
}