package org.victor.model;

public class Price {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Price.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Price.flightId
     *
     * @mbggenerated
     */
    private Integer flightid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Price.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Price.tax
     *
     * @mbggenerated
     */
    private String tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Price.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Price
     *
     * @mbggenerated
     */
    public Price(Integer id, Integer flightid, String price, String tax, String company) {
        this.id = id;
        this.flightid = flightid;
        this.price = price;
        this.tax = tax;
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Price
     *
     * @mbggenerated
     */
    public Price() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Price.id
     *
     * @return the value of Price.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Price.id
     *
     * @param id the value for Price.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Price.flightId
     *
     * @return the value of Price.flightId
     *
     * @mbggenerated
     */
    public Integer getFlightid() {
        return flightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Price.flightId
     *
     * @param flightid the value for Price.flightId
     *
     * @mbggenerated
     */
    public void setFlightid(Integer flightid) {
        this.flightid = flightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Price.price
     *
     * @return the value of Price.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Price.price
     *
     * @param price the value for Price.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Price.tax
     *
     * @return the value of Price.tax
     *
     * @mbggenerated
     */
    public String getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Price.tax
     *
     * @param tax the value for Price.tax
     *
     * @mbggenerated
     */
    public void setTax(String tax) {
        this.tax = tax == null ? null : tax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Price.company
     *
     * @return the value of Price.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Price.company
     *
     * @param company the value for Price.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }
}